apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-portfolio-api-ingress
  namespace: devops-portfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: devops-portfolio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-portfolio-api-service
                port:
                  number: 80
